apiVersion: v1
kind: Pod
metadata:
  name: pdfmagic
  labels:
    app: pdfmagic
spec:
  containers:
  - name: pdfmagic
    image: 0track/pdfmagic:latest
    resources:
      requests:
        cpu: 0.1
    ports:
    - containerPort: 8080
